# Generated by Django 3.2.8 on 2021-11-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_user_photo_author_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profile_picture',
            new_name='photo',
        ),
    ]
