# Generated by Django 3.2.8 on 2021-11-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_profile_picture_author_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='photo',
            new_name='profile_pic',
        ),
    ]
