# Generated by Django 3.2.8 on 2021-11-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_comment',
            field=models.IntegerField(default=0, verbose_name='Nombre de vue'),
        ),
    ]
