# Generated by Django 3.2.8 on 2021-11-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_view_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='view_comment',
            new_name='view_count',
        ),
    ]
