# Generated by Django 3.2.8 on 2021-11-02 09:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_rename_view_comment_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default=' ', verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=tinymce.models.HTMLField(default=' ', verbose_name='Apercu'),
        ),
    ]
