# Generated by Django 3.2.8 on 2021-11-02 10:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20211102_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default=' ', verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=tinymce.models.HTMLField(default=' ', verbose_name='Aperçu'),
        ),
    ]
