# Generated by Django 3.2.8 on 2021-11-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
            ],
            options={
                'verbose_name': 'Marketing',
                'verbose_name_plural': 'Marketings',
            },
        ),
    ]
